<?php
require("veza.php");
$upit="CREATE TABLE imenik_klijenti(klkln VARCHAR(12), idmon VARCHAR(4), nazkl TEXT, adrkl TEXT, mstkl TEXT, fiks TEXT, email TEXT, radvr VARCHAR(50), vrsta VARCHAR(1), gruob VARCHAR(2),gps TEXT,stat VARCHAR(1))";
$ishod=mysqli_query($con,$upit);
echo "formirana tabela";
$upit="CREATE TABLE imenik_akcija(klak VARCHAR(12),nazakc TEXT, kont TEXT)";
$ishod=mysqli_query($con,$upit);
echo "formirana tabela";
$upit="CREATE TABLE imenik_interni(klint VARCHAR(12),nazint TEXT,fiksni TEXT,mob1 TEXT,mob2 TEXT,oper VARCHAR(1),inti VARCHAR(1),serv VARCHAR(1))";
$ishod=mysqli_query($con,$upit);
echo "formirana tabela";
$upit="CREATE TABLE klijenti_slike(klkln VARCHAR(12), opis TEXT, link TEXT)";
$ishod=mysqli_query($con,$upit);
echo "formirana tabela";
$upit="CREATE TABLE klijenti_akcije(klkln VARCHAR(12),napo TEXT,akc1 TEXT,akc2 TEXT,akc3 TEXT,akc4 TEXT,akc5 TEXT)";
$ishod=mysqli_query($con,$upit);
echo "formirana tabela";
$upit="CREATE TABLE klijenti_kontakti(klkln VARCHAR(12),klkon VARCHAR(12),impre TEXT,fiks TEXT,mobi1 TEXT,mobi2 TEXT,pojm1 TEXT,pojm2 TEXT, poza TEXT)";
$ishod=mysqli_query($con,$upit);
echo "formirana tabela";
$upit="CREATE TABLE klijenti_oprema(klkln VARCHAR(12),nazop VARCHAR(12), kolop TEXT, link TEXT)";
$ishod=mysqli_query($con,$upit);
echo "formirana tabela";
$upit="CREATE TABLE klijenti_odsustva(klod VARCHAR(12),klkln VARCHAR(12),datodl VARCHAR(10),osoba TEXT,kont TEXT,stat VARCHAR(1))";
$ishod=mysqli_query($con,$upit);
echo "formirana tabela";
$upit="CREATE TABLE prijemi(klpr VARCHAR(12),datprp VARCHAR(10),vrmprp VARCHAR(5),brtel TEXT,impre TEXT,opis TEXT)";
$ishod=mysqli_query($con,$upit);
echo "formirana tabela";
$upit="CREATE TABLE alarmi_zapisi(klaz VARCHAR(12), klkln VARCHAR(12),dataz VARCHAR(10),vrmaz VARCHAR(10), zonaz VARCHAR(250),opaz TEXT,vrsaz VARCHAR(1),inter VARCHAR(1),poli VARCHAR(1))";
$ishod=mysqli_query($con,$upit);
echo "formirana tabela";
$upit="CREATE TABLE inter_zapisi(klin VARCHAR(12), klkln VARCHAR(12),nazint VARCHAR(12),datpmp VARCHAR(10),vrpmp VARCHAR(5),datdol VARCHAR(10), vrdol VARCHAR(5), zonit VARCHAR(250),opit TEXT,vrsit VARCHAR(1))";
$ishod=mysqli_query($con,$upit);
echo "formirana tabela";
$upit="CREATE TABLE inter_slike(klin VARCHAR(12), opis TEXT, link TEXT)";
$ishod=mysqli_query($con,$upit);
echo "formirana tabela";
$upit="CREATE TABLE obilasci(klkln VARCHAR(12), datob TEXT, vremob TEXT)";
$ishod=mysqli_query($con,$upit);
echo "formirana tabela";
$upit="CREATE TABLE tagovi(kltag VARCHAR(12),klkln VARCHAR(12),stat VARCHAR(1))";
$ishod=mysqli_query($con,$upit);
echo "formirana tabela";
$upit="CREATE TABLE servis(klsrv VARCHAR(12),klkln VARCHAR(12),datsrv TEXT,vremsrv TEXT,opsrv TEXT,vrsrv VARCHAR(1),stat VARCHAR(1))";
$ishod=mysqli_query($con,$upit);
echo "formirana tabela";
mysqli_close($con);
?>